.install_deps_template: &install_deps
  image: python:3.6
  before_script:
    - pip install -r requirements.txt

test:
  <<: *install_deps
  stage: test
  script:
    - python -m unittest
  variables:
    DJANGO_SETTINGS_MODULE: tests.settings
